### ISSUE TITLE
To do list semaine 16-22 oct

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/artisan2.0#16]
#- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Je comprends plus trop ou mettre les choses sur le Github Artisan 2.0... il y a bcp de dossiers et je passe parfois plus de temps à chercher les choses qu'à ajouter du contenu^^ Un conseil à me donner?

Du coup, je réunis ici la "to do list" pour cette semaine.

## objectif
- Préparation du Workshop N°3
- Avancement du hackaton

## proposition

- [x] créer event Facebook du 21 et 22 octobre
--> @Ginsburg tu peux le créer en privé et je le copie-colle comme les autres fois?

- [x] créer le mailchimp et envoyer à la liste de contact 
--> @Ginsburg tu peux le créer et je fais l'envoi?

- [x] confirmer avec Sam de Communa la dispo pour le 21/22 et en profiter pour les impliquer pour le hackaton 
--> Je lui envoie un mail dès que l'event Fb est créé (mais à priori aucun souci sauf le samedi ou faut p-e finir plus tôt)

- [x] voir avec Olivier, le cuisto de Communa si il peut prendre en charge la nourriture pour le 21/22 octobre (dimanche on pourrait aussi se mettre sur le brunch qui est déjà en place? mais c'est 12 euros... https://www.facebook.com/events/343614812710640/)
--> je le contact dès qu'on a un certain nombre d'inscrit sinon faudra trouver un plan B (voir avec Refresh?)

- [x] écrire un texte pour communiquer sur le hackaton + visuels
--> Je vous envoi un brouillon dans quelques jours

- [x] commencer à définir quelques aspects pratiques pour le hackaton (nombre de participants souhaité, lieux, contenu, matériel...)
--> On se fait un topo à 3 en fin de semaine?

- [x] envoyer un mail aux "relais" du hackaton pour qu'ils commencent à impliquer des gens (Fabienne de Re-sceptre, profs archi...)
--> J'envoie ça dès que j'ai écrit un texte sur le hackaton

- [x] relancer Baya pour leur dispo du 20 au 24 novembre
--> j'avais envoyé un mail il y a une semaine, sans réponse... pas plus simple/rapide de passer les voir sur place?

- [x] update le budget
--> @Ginsburg tu saurais créer un dossier où tous les coûts seraient repris?

**Comment by DewiBrunet** [comment]
C'est parti - 3 participants samedi, 3 dimanche, on s'améliore :) 
Pour la bouffe, je vais trouver un truc dans le quartier samedi et dimanche j'ai réservé pour le brunch sur place (12e/personne mais c'est plus sympa et on peux se permettre je penses comme le matériel est pas très cher).
Sinon pour le reste de la to do list, @nicolasdb et @Ginsburg on pourrait se faire un skype commun lundi pour discuter du hackaton?

**Comment by nicolasdb** [comment]
yup, rdv ce midi en mangeant. 
Vers 13h
