### ISSUE TITLE
To do list semaine 23-29 oct

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/artisan2.0#20]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Beaucoup de choses à faire pour préparer le hackthon qui est déjà dans un mois et on peux pas se permettre de tout faire une semaine avant comme avec les workshops...

Du coup, je réunis ici la "to do list" pour cette semaine. @nicolasdb est pas la de la semaine, à voir @Ginsburg sur quoi tu peut m'aider à avancer.

## objectif
Création de textes, visuels et prototypes pour la communication.
Contacter les personnes à impliquer

## proposition

- [x] écrire et valider un texte pour communiquer sur le hackaton + visuels
--> J'ai écris une version (faut accepter mes pull request ;) ), à voir si ça explique bien, si ça donne envie

- [x]  définir les aspects pratiques du hackaton (nombre de participants souhaité, lieux, contenu, matériel...)
--> Pareil, j'ai créé un .md "info pratique" qui reste à actualiser

- [x] Proposer à CIN de se charger de l'organisation de l'event

- [x]  proposer une réunion semaine prochaine (un midi) avec OpenFab, Communa, CIN, Baya (et la commune?)

- [x]  répondre à Baya pour leur dispo du 20 au 24 novembre et voir si le projet "abris portables" les intéresse 

- [x]  updater le budget (note de frais et coût prévisionnel pour voir combien on peux payer les gens/la location des lieux/la nourriture)

- [x] Créer un/plusieurs prototypes des objets à créer pour mieux communiquer (et en déposer chez Communa)
--> je m'en charge cette semaine

**Comment by nicolasdb** [comment]
Je pourrais relire des trucs mais étant sur des workshops tous les jours jusqu'à dimanche, je n'aurai qu'un peu de tps en fin d'aprem normalement. entre workshop et repas, ensuite ce sera surement à base de kronembourg jusqu'au dodo. ^^
