### ISSUE TITLE
Implication membres OpenFab

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/artisan2.0#22]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Plusieurs membres veulent s'impliquer dans le Hackathon Artisan 2.0.

## objectif
- Montrer que s'impliquer chez OpenFab c'est trop cool et c'est récompensé!
- Tester les méthodes de rémunération/avantages en fonction du type de membre (cf [gamification](https://github.com/openfab-lab/gamification-fablab/blob/master/Gamification%20Guide.md))

## proposition
Niveau budget sur le hackathon on pourrait je pense dégager  (cf [Budget](https://github.com/openfab-lab/artisan2.0/blob/master/Projet/Budget.md)) : 
- 800€ pour l'organisation
- 1400€ pour l'animation (4 jours 1 animateur)

En fonction du type de membre, on pourrait proposer : 
- User : accès aux dés bières/abonnement mensuel
- SuperUser : accès aux dés bières/abonnement mensuel/crédits
- MetaUser : accès aux dés bières/abonnement mensuel/crédits/rémunération

Questions : 
- Comment "traduire" des € en dés bières/crédits/abonnement? (surtout si c'est 1400€, ça peut faire beaucoup de bières^^).
- Comment proposer des avantages win-win pour OpenFab et le membre : badge animation/organisation? implication future dans fablab mobile?

**Comment by nicolasdb** [comment]
Convertir des € en crrr ou débière ou autres cartes? 
le problème c'est que pour justifier les dépenses, ça doit passer par des factures et on ne peut facturer d'openfab à openfab. 

On peut par contre, créer de la valeur interne tant que ça ne "coûte" rien à l'asbl. Faut aussi le documenter mais on pourrait imaginer créer 1000 crrr, dont 500 serai des cartes. 
C'est la mise initiale, un investissement de test d'un équivalent virtuel de 1000€. 
Il faudrait alors suivre l'évolution de cette valeur sachant que pour 
- les crrr, la valeur est fixe
- les débières, la valeur est variable entre 0 et 3€ mais qu'à l'achat on est à +- 0,50€ la bouteille de maes.
Quelle probabilité a-t-on à chaque tirage? Risque de perte pour Openfab?
25% de chance Epic Fail mais 75% de chance d'au moins avoir 1 bière gratuite dont 25% d'en avoir 2 et 25% d'en avoir 3. 
https://fr.wikihow.com/calculer-les-probabilit%C3%A9s
Le gain pour Openfab est de toutes façons plus large que le coût en bière puisqu'on récompense des actions et donc une potentielle rémunération horaire. 
Les pertes sont aussi très probablement couverte par les consommations hors jeu à 1€. 
Comment mieux en mesurer l'impact? Y a t'il des mathématiciens dans la sale?
https://www.youtube.com/watch?v=ntNF_VIYexQ

- idem avec les cartes D6,8,12 et 20.  
http://gwydir.demon.co.uk/jo/probability/calcdice.htm

Mais c'est une bonne occasion de produire une quantité fixe et voir ce qu'il en ressort. 
Je ne pense pas qu'il y a de risque de perdre d'argent tant qu'on ne converti pas les crrr gagné en €. 
Et comme on a dit, facturer c'est retirer TVA et taxes de la valeur de départ. c'est un incitant à garder la monnaie sous sa forme locale.

**Comment by nicolasdb** [comment]
pour ce qui est des répartitions, 
mettons sur la table ce qu'on a et discutons. :)
