### ISSUE TITLE
To do Hackathon

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/artisan2.0#24]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
C'est dans une semaine, il y a plein de choses à faire!
## objectif
Que le hackathon soit réussit (et avoir des participants surtout^^)
### Communication
- Flyers
- [ ] Ecoles (Beaux-Arts, St Luc, La Cambre, 75…)
--> Anne-Sophie
- [x] Boites aux lettres périmètre Contrat De Quartier 
-->Anne-Sophie à droite, Dewi à gauche (+/-200 ?)

- Mail
- [ ] Réseaux personnel 
--> Sarah/Anne-Sophie/Dewi
- [x] Réseaux anciens participants Artisan 2.0
--> Dewi

- Facebook
- [x] Inviter full monde sur l’event

Updates régulières : 
- [x] achat matériel
- [ ] supers animateurs
- [ ] supers challengeurs
- [x] récompenseS
- [x] photos anciens workshops
- [x] autres projets pliés inspirants
- [ ] plus que 3 places… 
--> Dewi

- Plateforme (Que Faire, Smart…)  - [ ] 
--> Anne-Sophie/Dewi

### Organisation en amont
- Achat matériel
- [x] Achat mercredi 22/11 (led, papiers, embossoirs, moules MDF, pinces, PV…)
--> Sarah
- [x]  Amener une bibliothèque de matériaux disponibles 
--> Dewi/Anne-Sophie

### Récompenses
- [ ] OpenFab (abo annuel + 1 journée + 10 crr)
- [x] 1 repas chez Refresch x participant
--> Nico
- [ ] 1 panier chez l’Heureux Nouveau x participant
--> Sarah

- [x] Expo
--> Sarah

### Repas
- [ ] Contact Olivier de Communa pour au moins 2 jours, 5 à 10 personnes
--> Dewi

**Comment by nicolasdb** [comment]
Laurent de Refresh nous offrent 5 repas végétarien, valable 3 mois.  
On doit lui proposer une petite carte pour ce cadeau. Je pense qu'un petit template pour refaire ça par après à d'autres occasions peut lui faire plaisir. 

Mais Quid du Plan B? à qui ont remet 5 repas? En même tps, ça fait plaisir et si personne ne les utilisent, c'est pas gâché.
