### ISSUE TITLE
Plan B

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/artisan2.0#25]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Le hackathon est dans 4 jours et on a toujours que 1 inscrit... Rien n'est joué et on peut avoir des surprises mais prévoyons le pire ;) 

## objectif
Réfléchir aux plans B, transformer le problème en opportunité.
Profiter de 4 jours de création avec 1 inscrit + 2 animateurs.
Ne pas faire un bad buzz.

## proposition
- On annule et on reporte sous forme de workshops de 1 ou 2 jours?
- On demande à la commune si ils ont pas une idée d'application concrète à faire dans le quartier? (ex : conception de 10 lampions à accrocher sur un bâtiment)
- On profite de la visibilité de Gallerie Ranvenstein pour faire une expo sur le processus de création?
- On ouvre le hackathon en mode gratuit pour avoir des implications régulières d'autres personnes?

**Comment by DewiBrunet** [comment]
L'objectif du projet Artisan 2.0 est de faire découvrir les technologies, d'en dévoiler les opportunités pour les artisans, le plus possible pour les gens du quartier. Si personne ne veut participer à un workshop de 4 jours, un certain nombre on fait part de leur intérêt pour le projet (et pour acheter des produits finis). Donc, faire participer à des workshops n’est peut-être pas la meilleure approche ici, testons autre chose!

Hackons le hackathon pour le transformer en : 

1. Atelier de production
En 4 jours, on peut designer et produire une série capsule de genre 10 lampions. On peut alors les vendre (et reverser la tune à des initiatives citoyennes du quartier?) ou les placer/offrir à des organismes du Contrat de Quartier pour leur donner une visibilité avec une signalétique originale. On pourrait aussi vendre des kits pour confectionner soi-même ses lampions.

2. Vitrine de création
On communique et on documente au maximum durant le hackathon pour donner de la visibilité au projet. On prépare au mieux une présentation pour le Récup Day et l'exposition Gallerie Ravenstein. On produit une vidéo trop stylée et on fait le buzz!

**Comment by Valonlisbeth** [comment]
Peut être que "redistribuer l'argent aux initiatives citoyennes" serait trop compliqué : qui va gérer la comptabilité? comment? sur base de quoi, il faudra donner des sous à un tel et pas à un autre? Autant offrir les lampes ou même organiser un grand repas de Noël en invitant les habitants avec la recette des ventes... c'est plus simple.
Pour le Hackaton lui même, comment cela va t il se passer? vu que ça devient une chaîne de production, il y aura  t il une rémunération pour les participants à la cette commande?
Questions questions!^^
