### ISSUE TITLE
Lieu - Appeler Communa et Baya

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/artisan2.0#3]
- [ ] ref to file .md or pullRequest #: 
- Fichier qui réunit les différentes infos sur les lieux : https://github.com/openfab-lab/artisan2.0/blob/master/Projet/Lieu.md
*(à remplir quand l'issue est résolue)*
## contexte
OpenFab est hors de la zone du contrat de quartier, voir avec Communa et Baya qui le sont.
## proposition
Appeler Communa et Baya --> voir tarifs (12€/h ?), dispo, ...
Voir si cela correspond au besoin d'équipement.
Que hackathon ou workshops aussi ?

**Comment by Ginsburg** [comment]
Qui s'y colle, c'est quoi les contacts ?
Le doc spécial lieu à compléter : https://github.com/openfab-lab/artisan2.0/blob/master/Projet/Lieu.md

**Comment by DewiBrunet** [comment]
C’est un point essentiel pour la commune, « ... une attention avait été soulevée quant aux efforts qui seraient faits pour s'adresser au quartier et aux moins favorisés... ».

Communa me semble le bon lieu, en lien direct avec le CQD ([Garage Gray](http://quartiers.brussels/1/qp/1090) , [Entre Deux Ponts](http://quartiers.brussels/1/qp/1087)).
Encore mieux si on peut intégrer Communa dans la promotion et le contenu des workshops pour des publics variés.

Faut leur demander la dispo pour le w-e du 14/15 septembre (voire faire demi-journée chez Baya ?), la place qu’ils ont, leur tarif et si ils ont 4 grandes tables+8 chaises.

Je peux voir ça demain si j’ai le contact.

**Comment by DewiBrunet** [comment]
(au moins pour le prochain workshop car on peut préparer à l'avance les "moules" en MDF à la laser de OpenFab et les amener sur place pour garder le 2.0)
