### ISSUE TITLE
Workshop02 - Billetterie 

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/artisan2.0#4]
- [ ] ref to file .md or pullRequest #: .................................................  

## contexte
En lien avec cette [issue pour le Workshop01](https://github.com/openfab-lab/openfab/issues/162), la solution semble satisfaisante. Profiter du formulaire d'inscription pour demander d'où vient le participant ?
## proposition
Refaire un Weezevent en retravaillant le formulaire d'inscription pour avoir un peu plus d'infos sur les participants : 
- Demander si habitant du quartier Maelbeek (est-ce que c'est bien identifié par les habitants ?) ? Si habitant d'Ixelles ?
- Préférences alimentaires ?

Discussion en cours sur l'[issue précédente pour le Workshop01](https://github.com/openfab-lab/openfab/issues/162)

**Comment by DewiBrunet** [comment]
Si on peux demander plus d'info c'est mieux : 
- age
- profession 
- nom de la rue où vous habitez
- avez-vous des préférences alimentaires?
