### ISSUE TITLE
Workshop02 - Thème ?

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/artisan2.0#5]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*
## contexte
Volonté que les workshops servent d'exploration vers le hackathon (jeu sur la contrainte, différences de taille, matériau)
Proposition de faire ça sur "l'abris" qui est plus documenté que "la capuche" (workshop03)
## proposition
Comment rendre ça vendeur ? Faut-il un autre mot qu'abris ?

Autant pour capuche on peut parler d'abat-jour éventuellement, même si ça ne se limite pas à ça. Autant abris je vois moins.

**Comment by DewiBrunet** [comment]
Après discussion on pencherait donc sur une mini serre à déplier pour les balconières.
A coupler avec la possibilité de la faire en papier pour créer une lampe (plus facile et plus rapide!)?

Le pliage Yoshimura permet de travailler à échelle micro/meso/macro (possibilité de créer un abri... disons plutôt le cocon ou la capsule?) 

L'avantage de la mini serre est que : 
-c'est faisable en une journée
-ça peut être fait où on veut, pourquoi pas dehors?^^ (préparer les moules MDF en avance)
-ça développe la verdure (lien avec espace public, initiatives citoyennes...)
-ça encourage "l'alimentation durable et la création, deux filières bien développées dans le quartier" (#[Entre Deux Ponts](http://quartiers.brussels/1/qp/1087))
-ça nous permet de teaser l'aquaponie :)

**Comment by DewiBrunet** [comment]
Je propose de teaser comme ceci :
"Ce workshop vous fera découvrir l'artisanat 2.0 au travers du pliage pour réaliser une mini serre. L’objectif est d’encourager l’autoproduction à échelle locale, fleurir les balcons ou encore favoriser le développement de végétation dans le quartier d’Ixelles."
