### ISSUE TITLE
Workshop02 - Communication

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/artisan2.0#6]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

**Comment by DewiBrunet** [comment]
J'ai copié collé ce que tu avais fait pour l'event Fb précédant en enlevant la partie "accès aux outils numériques » (si c’est pas à l’OpenFab), mettant en avant le CQD, changement date…
Faudra juste vérifier pour en créer 2 events séparés du coup?

Event Fb :

Visuel :
#163

Nom de l’évènement :
Workshop # 2 Artisan 2.0 par OpenFab

Lieu :
Communa

Date/Heure :
14/10/2017 - 10h - 18h

Description :
INFOS PRATIQUES :

Date : début 10h, samedi 14/10/17
Inscription obligatoire :
Prix : 10€
Participants : 8 maximum
Repas inclus
Matériaux inclus

Dans le cadre du Contrat de Quartier Durable Maelbeek de la commune d'Ixelles.
Artisan 2.0 est l'occasion d'explorer les possibilités que peut apporter la technologie aux techniques artisanales. Comment réaliser ses projets plus efficacement ? Comment innover ? Comment combiner des savoirs, des techniques ?
Ce workshop vous fera découvrir l'artisanat 2.0 au travers du pliage pour réaliser une mini serre. L’objectif est d’encourager l’autoproduction à échelle locale, fleurir les balcons ou encore favoriser le développement de végétation dans le quartier d’Ixelles.

Journée en 4 parties :

matin : découvrez le travail de Dewi Brunet, artiste plieur et artisan 2.0 qui mêle technique traditionnelle et technologie pour aller plus loin dans son travail.

midi : et si on cuisinait ? un temps de convivialité, discussion autour d'un bon repas : quels sont vos projets ? comment pourrait-on utiliser la technologie dans vos projets ? comment le FabLab peut vous aider ?

après-midi : essayez-vous à l'artisanat 2.0 et apprendrez des techniques d’origami pour plier une serre portable ou un luminaire.

Artisan 2.0 ce seront aussi 2 autres sessions de workshops pour aller plus loin :

21/22 octobre
20/24 novembre : un format 4 jours (hackathon) pour aller plus loin dans les applications.
Plus d'infos à venir sur la page OpenFab !

**Comment by nicolasdb** [comment]
> essayez-vous à l'artisanat 2.0 et **apprendrez** des techniques d’origami pour plier une serre portable ou un luminaire.

il manque pas quelque chose? et c'est sur evensi aussi.
