### ISSUE TITLE
Workshop02 - Repas

### ISSUE THREAD

**Issue by Ginsburg** [openfab-lab/artisan2.0#7]
- [ ] ref to file .md or pullRequest #: .................................................  
*(à remplir quand l'issue est résolue)*

**Comment by nicolasdb** [comment]
Voici le contact pour le cuisinier qui est à Communa. 

---------- Message transféré ----------
De : Olivier Goris <gorisolivier@gmail.com>
Date : 4 octobre 2017 à 19:33
Objet : Atelier octobre
À : nicolas@openfab.be


Salut Nicolas,

Sympa que tu sois passée avec l'équipe des Jacqueline ce midi ! Je suis vraiment étonné chaque jour des chouettes rencontres et de l'écosystème qui s'y crée ! 

C'est avec plaisir que je ferai des "extra" de cuisine, le tout est de voir quand et pour combien de personnes... et si je suis dispo également ! 

Merci à toi et à bientôt, faut que je vienne visiter ce FabLab (pas comme les autres).


Oli




Olivier Goris
0499/124.115
https://www.facebook.com/LoustaouCuisine/
